In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Medicare_Physician_and_Other_Supplier_National_Provider_Identifier__NPI__Aggregate_Report__Calendar_Year_2014.csv")

C:\Users\Vignesh\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [74]:
df.head()

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,Percent (%) of Beneficiaries Identified With Depression,Percent (%) of Beneficiaries Identified With Diabetes,Percent (%) of Beneficiaries Identified With Hyperlipidemia,Percent (%) of Beneficiaries Identified With Hypertension,Percent (%) of Beneficiaries Identified With Ischemic Heart Disease,Percent (%) of Beneficiaries Identified With Osteoporosis,Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis,Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders,Percent (%) of Beneficiaries Identified With Stroke,Average HCC Risk Score of Beneficiaries
0,1659374411,MAHR,TODD,A,MD,M,I,1836 SOUTH AVE,NaN,LA CROSSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.1238
1,1073738571,GIBB,JOYCE,E,CRNP,F,I,215 ALLEGHENY AVE,NaN,OAKMONT,...,37.0,NaN,NaN,57.0,NaN,NaN,37.0,NaN,NaN,0.9576
2,1619972387,DEEM,ROBERT,B,M.D.,M,I,1549 S JEFFERSON,NaN,MONTICELLO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.6467
3,1265649073,GAMBLE,SARAH,M,DO,F,I,222 RAILROAD AVE,SUITE B,GREENWICH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.9607
4,1366640377,DIRKS,ZACHARY,B,O.D.,M,I,320 SUNRISE DR,NaN,SAINT PETER,...,22.0,26.0,32.0,34.0,12.0,NaN,17.0,27.0,NaN,0.9950

In [75]:
len(df)

986677

In [76]:
df.columns

Index(['National Provider Identifier',
       'Last Name/Organization Name of the Provider',
       'First Name of the Provider', 'Middle Initial of the Provider',
       'Credentials of the Provider', 'Gender of the Provider',
       'Entity Type of the Provider', 'Street Address 1 of the Provider',
       'Street Address 2 of the Provider', 'City of the Provider',
       'Zip Code of the Provider', 'State Code of the Provider',
       'Country Code of the Provider', 'Provider Type of the Provider',
       'Medicare Participation Indicator', 'Number of HCPCS',
       'Number of Services', 'Number of Medicare Beneficiaries',
       'Total Submitted Charge Amount', 'Total Medicare Allowed Amount',
       'Total Medicare Payment Amount',
       'Total Medicare Standardized Payment Amount', 'Drug Suppress Indicator',
       'Number of HCPCS Associated With Drug Services',
       'Number of Drug Services',
       'Number of Medicare Beneficiaries With Drug Services',
       'Total Drug Submitted Charge Amount',
       'Total Drug Medicare Allowed Amount ',
       'Total Drug Medicare Payment Amount ',
       'Total Drug Medicare Standardized Payment Amount',
       'Medical Suppress Indicator',
       'Number of HCPCS Associated With Medical Services',
       'Number of Medical Services',
       'Number of Medicare Beneficiaries With Medical Services',
       'Total Medical Submitted Charge Amount',
       'Total Medical Medicare Allowed Amount',
       'Total Medical Medicare Payment Amount',
       'Total Medical Medicare Standardized Payment Amount',
       'Average Age of Beneficiaries', 'Number of Beneficiaries Age Less 65',
       'Number of Beneficiaries Age 65 to 74',
       'Number of Beneficiaries Age 75 to 84',
       'Number of Beneficiaries Age Greater 84',
       'Number of Female Beneficiaries', 'Number of Male Beneficiaries',
       'Number of Non-Hispanic White Beneficiaries',
       'Number of Black or African American Beneficiaries',
       'Number of Asian Pacific Islander Beneficiaries',
       'Number of Hispanic Beneficiaries',
       'Number of American Indian/Alaska Native Beneficiaries',
       'Number of Beneficiaries With Race Not Elsewhere Classified',
       'Number of Beneficiaries With Medicare Only Entitlement',
       'Number of Beneficiaries With Medicare & Medicaid Entitlement',
       'Percent (%) of Beneficiaries Identified With Atrial Fibrillation',
       'Percent (%) of Beneficiaries Identified With Alzheimerâ€™s Disease or Dementia ',
       'Percent (%) of Beneficiaries Identified With Asthma ',
       'Percent (%) of Beneficiaries Identified With Cancer ',
       'Percent (%) of Beneficiaries Identified With Heart Failure ',
       'Percent (%) of Beneficiaries Identified With Chronic Kidney Disease',
       'Percent (%) of Beneficiaries Identified With Chronic Obstructive Pulmonary Disease',
       'Percent (%) of Beneficiaries Identified With Depression ',
       'Percent (%) of Beneficiaries Identified With Diabetes ',
       'Percent (%) of Beneficiaries Identified With Hyperlipidemia ',
       'Percent (%) of Beneficiaries Identified With Hypertension ',
       'Percent (%) of Beneficiaries Identified With Ischemic Heart Disease ',
       'Percent (%) of Beneficiaries Identified With Osteoporosis ',
       'Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis ',
       'Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders ',
       'Percent (%) of Beneficiaries Identified With Stroke ',
       'Average HCC Risk Score of Beneficiaries '],
      dtype='object')

In [77]:
li = df["Provider Type of the Provider"].unique()

In [78]:
print(li)

['Allergy/Immunology' 'Nurse Practitioner' 'Family Practice'
 'Internal Medicine' 'Optometry' 'Physician Assistant' 'Psychiatry'
 'Orthopedic Surgery' 'Obstetrics/Gynecology' 'Pediatric Medicine'
 'Urology' 'Radiation Oncology' 'Physical Therapist' 'Podiatry'
 'Dermatology' 'Emergency Medicine' 'General Practice' 'Neurology'
 'General Surgery' 'Rheumatology' 'Chiropractic' 'Otolaryngology'
 'Infectious Disease' 'Endocrinology' 'Centralized Flu' 'Ophthalmology'
 'Anesthesiology' 'Cardiology' 'Maxillofacial Surgery'
 'Hematology/Oncology' 'Diagnostic Radiology' 'Gastroenterology' 'CRNA'
 'Plastic and Reconstructive Surgery'
 'Physical Medicine and Rehabilitation' 'Sports Medicine'
 'Licensed Clinical Social Worker' 'Pathology'
 'Mass Immunization Roster Biller' 'Addiction Medicine' 'Pain Management'
 'Independent Diagnostic Testing Facility' 'Clinical Psychologist'
 'Certified Nurse Midwife' 'Pulmonary Disease' 'Gynecological/Oncology'
 'Vascular Surgery' 'Certified Clinical Nurse Specialist'
 'Audiologist (billing independently)' 'Preventive Medicine' 'Nephrology'
 'Occupational therapist' 'All Other Suppliers' 'Neurosurgery'
 'Public Health Welfare Agency' 'Ambulatory Surgical Center'
 'Medical Oncology' 'Ambulance Service Supplier'
 'Speech Language Pathologist' 'Oral Surgery (dentists only)'
 'Nuclear Medicine' 'Registered Dietician/Nutrition Professional'
 'Osteopathic Manipulative Medicine' 'Surgical Oncology'
 'Thoracic Surgery' 'Clinical Laboratory' 'Critical Care (Intensivists)'
 'Unknown Physician Specialty Code' 'Cardiac Electrophysiology'
 'Geriatric Medicine' 'Hand Surgery'
 'Multispecialty Clinic/Group Practice' 'Cardiac Surgery'
 'Anesthesiologist Assistants' 'Interventional Radiology'
 'Psychologist (billing independently)' 'Interventional Pain Management'
 'Hospice and Palliative Care' 'Hematology' 'Sleep Medicine'
 'Colorectal Surgery (formerly proctology)' 'Geriatric Psychiatry'
 'Peripheral Vascular Disease' 'Portable X-ray' 'Neuropsychiatry'
 'Radiation Therapy' 'Mammographic Screening Center'
 'Slide Preparation Facility' 'Unknown Supplier/Provider' 'Pharmacy'
 'Interventional Cardiology']

In [79]:
print("Cardiologists" in li)

False

In [80]:
df.loc[df['Provider Type of the Provider'] == "Allergy/Immunology", ['Provider Type of the Provider']] = "Allergists"

In [81]:
df.loc[df['Provider Type of the Provider'] == "Endocrinology", ['Provider Type of the Provider']] = "Endocrinologists"

In [82]:
df.loc[df['Provider Type of the Provider'] == "Gastroenterology", ['Provider Type of the Provider']] = "Gastroenterologists"

In [83]:
df.loc[df['Provider Type of the Provider'] == "Nephrology", ['Provider Type of the Provider']] = "Nephrologists"

In [84]:
df.loc[df['Provider Type of the Provider'] == "Urology", ['Provider Type of the Provider']] = "Urologists"

In [85]:
df.loc[df['Provider Type of the Provider'] == "Pulmonary Disease", ['Provider Type of the Provider']] = "Pulmonologists"

In [86]:
df.loc[df['Provider Type of the Provider'] == "Otolaryngology", ['Provider Type of the Provider']] = "Otolaryngologists"

In [87]:
df.loc[df['Provider Type of the Provider'] == "Neurology", ['Provider Type of the Provider']] = "Neurologists"

In [88]:
df.loc[df['Provider Type of the Provider'] == "Neurosurgery", ['Provider Type of the Provider']] = "Neurologists"

In [89]:
df.loc[df['Provider Type of the Provider'] == "Psychiatry", ['Provider Type of the Provider']] = "Psychiatrists"

In [90]:
df.loc[df['Provider Type of the Provider'] == "Clinical Psychologist", ['Provider Type of the Provider']] = "Psychiatrists"

In [91]:
df.loc[df['Provider Type of the Provider'] == "Hematology/Oncology", ['Provider Type of the Provider']] = "Oncologists"

In [92]:
df.loc[df['Provider Type of the Provider'] == "Medical Oncology", ['Provider Type of the Provider']] = "Oncologists"

In [93]:
df.loc[df['Provider Type of the Provider'] == "Gynecological/Oncology", ['Provider Type of the Provider']] = "Oncologists"

In [94]:
df.loc[df['Provider Type of the Provider'] == "Diagnostic Radiology", ['Provider Type of the Provider']] = "Radiologists"

In [95]:
df.loc[df['Provider Type of the Provider'] == "Interventional Radiology", ['Provider Type of the Provider']] = "Radiologists"

In [96]:
df.loc[df['Provider Type of the Provider'] == "Rheumatology", ['Provider Type of the Provider']] = "Rheumatologists"

In [97]:
df.loc[df['Provider Type of the Provider'] == "General Surgery", ['Provider Type of the Provider']] = "General surgeons"

In [98]:
df.loc[df['Provider Type of the Provider'] == "Plastic and Reconstructive Surgery", ['Provider Type of the Provider']] = "Orthopedic surgeons"

In [99]:
df.loc[df['Provider Type of the Provider'] == "Cardiac Surgery", ['Provider Type of the Provider']] = "Cardiac surgeons"

In [100]:
df.loc[df['Provider Type of the Provider'] == "Maxillofacial Surgery", ['Provider Type of the Provider']] = "Oral and maxillofacial surgeons"

In [101]:
df.loc[df['Provider Type of the Provider'] == "Obstetrics/Gynecology", ['Provider Type of the Provider']] = "Gynecologist"

In [102]:
df.loc[df['Provider Type of the Provider'] == "Pediatric Medicine", ['Provider Type of the Provider']] = "Pediatrician"

In [103]:
df.loc[df['Provider Type of the Provider'] == "Anesthesiology", ['Provider Type of the Provider']] = "Anesthesiologists"

In [104]:
df.loc[df['Provider Type of the Provider'] == "Anesthesiologist Assistants", ['Provider Type of the Provider']] = "Anesthesiologists"

In [105]:
df.loc[df['Provider Type of the Provider'] == "Podiatry", ['Provider Type of the Provider']] = "Podiatrist"

In [106]:
df.loc[df['Provider Type of the Provider'] == "Registered Dietician/Nutrition Professional", ['Provider Type of the Provider']] = "Bariatrician"

In [107]:
li_specialty = ['Allergists', 'Endocrinologists', 'Gastroenterologists', 'Nephrologists', 'Urologists', 'Pulmonologists', 'Otolaryngologists', 'Neurologists', 'Neurologists', 'Psychiatrists', 'Psychiatrists', 'Oncologists', 'Oncologists', 'Oncologists', 'Radiologists', 'Radiologists', 'Rheumatologists', 'General surgeons', 'Orthopedic surgeons', 'Cardiac surgeons', 'Oral and maxillofacial surgeons', 'Gynecologist', 'Pediatrician', 'Anesthesiologists', 'Anesthesiologists', 'Podiatrist', 'Bariatrician']

In [108]:
li_specialty = list(set(li_specialty))

In [109]:
print(li_specialty)

['Endocrinologists', 'Neurologists', 'General surgeons', 'Orthopedic surgeons', 'Bariatrician', 'Pulmonologists', 'Psychiatrists', 'Gynecologist', 'Allergists', 'Urologists', 'Cardiac surgeons', 'Nephrologists', 'Otolaryngologists', 'Oncologists', 'Anesthesiologists', 'Podiatrist', 'Oral and maxillofacial surgeons', 'Radiologists', 'Rheumatologists', 'Pediatrician', 'Gastroenterologists']

In [110]:
li = df["Provider Type of the Provider"].unique()

In [111]:
print(li)

['Allergists' 'Nurse Practitioner' 'Family Practice' 'Internal Medicine'
 'Optometry' 'Physician Assistant' 'Psychiatrists' 'Orthopedic Surgery'
 'Gynecologist' 'Pediatrician' 'Urologists' 'Radiation Oncology'
 'Physical Therapist' 'Podiatrist' 'Dermatology' 'Emergency Medicine'
 'General Practice' 'Neurologists' 'General surgeons' 'Rheumatologists'
 'Chiropractic' 'Otolaryngologists' 'Infectious Disease'
 'Endocrinologists' 'Centralized Flu' 'Ophthalmology' 'Anesthesiologists'
 'Cardiology' 'Oral and maxillofacial surgeons' 'Oncologists'
 'Radiologists' 'Gastroenterologists' 'CRNA' 'Orthopedic surgeons'
 'Physical Medicine and Rehabilitation' 'Sports Medicine'
 'Licensed Clinical Social Worker' 'Pathology'
 'Mass Immunization Roster Biller' 'Addiction Medicine' 'Pain Management'
 'Independent Diagnostic Testing Facility' 'Certified Nurse Midwife'
 'Pulmonologists' 'Vascular Surgery' 'Certified Clinical Nurse Specialist'
 'Audiologist (billing independently)' 'Preventive Medicine'
 'Nephrologists' 'Occupational therapist' 'All Other Suppliers'
 'Public Health Welfare Agency' 'Ambulatory Surgical Center'
 'Ambulance Service Supplier' 'Speech Language Pathologist'
 'Oral Surgery (dentists only)' 'Nuclear Medicine' 'Bariatrician'
 'Osteopathic Manipulative Medicine' 'Surgical Oncology'
 'Thoracic Surgery' 'Clinical Laboratory' 'Critical Care (Intensivists)'
 'Unknown Physician Specialty Code' 'Cardiac Electrophysiology'
 'Geriatric Medicine' 'Hand Surgery'
 'Multispecialty Clinic/Group Practice' 'Cardiac surgeons'
 'Psychologist (billing independently)' 'Interventional Pain Management'
 'Hospice and Palliative Care' 'Hematology' 'Sleep Medicine'
 'Colorectal Surgery (formerly proctology)' 'Geriatric Psychiatry'
 'Peripheral Vascular Disease' 'Portable X-ray' 'Neuropsychiatry'
 'Radiation Therapy' 'Mammographic Screening Center'
 'Slide Preparation Facility' 'Unknown Supplier/Provider' 'Pharmacy'
 'Interventional Cardiology']

In [40]:
df.drop(df[df['Age'] < 25].index, inplace = True)

KeyError: 'Age'

In [112]:
for i in li:
    if i not in li_specialty:
        df.drop(df[df["Provider Type of the Provider"] == i].index, inplace = True)

In [113]:
df

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,Percent (%) of Beneficiaries Identified With Depression,Percent (%) of Beneficiaries Identified With Diabetes,Percent (%) of Beneficiaries Identified With Hyperlipidemia,Percent (%) of Beneficiaries Identified With Hypertension,Percent (%) of Beneficiaries Identified With Ischemic Heart Disease,Percent (%) of Beneficiaries Identified With Osteoporosis,Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis,Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders,Percent (%) of Beneficiaries Identified With Stroke,Average HCC Risk Score of Beneficiaries
0,1659374411,MAHR,TODD,A,MD,M,I,1836 SOUTH AVE,NaN,LA CROSSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.1238
10,1851339485,MEDHEKAR,ANJALI,NaN,MD,F,I,4 ALLEGHENY CTR,8TH FLOOR,PITTSBURGH,...,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2923
13,1437336070,BOWERS-ZAMANI,ALYSSA,C,MD,F,I,777 HEMLOCK ST,NaN,MACON,...,20.0,22.0,57.0,61.0,16.0,NaN,35.0,NaN,0.0,0.9534
14,1083781983,DODD,NANCY,D,MD,F,I,441 N LAKEVIEW AVE,NaN,ANAHEIM,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.7349
29,1427038199,KRUMHOLZ,BARRY,M,MD,M,I,1920 E BASELINE RD,NaN,TEMPE,...,NaN,48.0,38.0,70.0,29.0,NaN,26.0,NaN,NaN,1.0743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986658,1144384918,DOROUGH,DAVID,W,MD,M,I,722 MEDICAL CENTER DR EAST # 101,NaN,CLOVIS,...,NaN,NaN,55.0,59.0,NaN,NaN,34.0,0.0,NaN,0.7177
986659,1316942584,LOONEY,JEFFREY,R,MD,M,I,350 STEELES RD,UNIT 1,BRISTOL,...,33.0,35.0,55.0,69.0,14.0,NaN,45.0,NaN,0.0,0.8282
986666,1235359209,HILD,KERRI,A,MD,F,I,3232 E MURDOCK ST,NaN,WICHITA,...,33.0,29.0,40.0,62.0,NaN,NaN,31.0,0.0,NaN,0.7658
986674,1124087143,MOULI,KONDA,B,MD,M,I,777 KIMOLE LN,SUITE 260,ADRIAN,...,18.0,33.0,58.0,70.0,38.0,5.0,39.0,3.0,3.0,1.1363
986675,1366635161,DRAGHINAS,DAVID,NaN,M.D.,M,I,34800 BOB WILSON DR,NMCSD,SAN DIEGO,...,35.0,33.0,53.0,75.0,53.0,11.0,39.0,NaN,NaN,1.4547

In [114]:
df.drop(df[df["Entity Type of the Provider"] == 'o'].index, inplace = True)

In [115]:
df

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,Percent (%) of Beneficiaries Identified With Depression,Percent (%) of Beneficiaries Identified With Diabetes,Percent (%) of Beneficiaries Identified With Hyperlipidemia,Percent (%) of Beneficiaries Identified With Hypertension,Percent (%) of Beneficiaries Identified With Ischemic Heart Disease,Percent (%) of Beneficiaries Identified With Osteoporosis,Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis,Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders,Percent (%) of Beneficiaries Identified With Stroke,Average HCC Risk Score of Beneficiaries
0,1659374411,MAHR,TODD,A,MD,M,I,1836 SOUTH AVE,NaN,LA CROSSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.1238
10,1851339485,MEDHEKAR,ANJALI,NaN,MD,F,I,4 ALLEGHENY CTR,8TH FLOOR,PITTSBURGH,...,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2923
13,1437336070,BOWERS-ZAMANI,ALYSSA,C,MD,F,I,777 HEMLOCK ST,NaN,MACON,...,20.0,22.0,57.0,61.0,16.0,NaN,35.0,NaN,0.0,0.9534
14,1083781983,DODD,NANCY,D,MD,F,I,441 N LAKEVIEW AVE,NaN,ANAHEIM,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.7349
29,1427038199,KRUMHOLZ,BARRY,M,MD,M,I,1920 E BASELINE RD,NaN,TEMPE,...,NaN,48.0,38.0,70.0,29.0,NaN,26.0,NaN,NaN,1.0743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986658,1144384918,DOROUGH,DAVID,W,MD,M,I,722 MEDICAL CENTER DR EAST # 101,NaN,CLOVIS,...,NaN,NaN,55.0,59.0,NaN,NaN,34.0,0.0,NaN,0.7177
986659,1316942584,LOONEY,JEFFREY,R,MD,M,I,350 STEELES RD,UNIT 1,BRISTOL,...,33.0,35.0,55.0,69.0,14.0,NaN,45.0,NaN,0.0,0.8282
986666,1235359209,HILD,KERRI,A,MD,F,I,3232 E MURDOCK ST,NaN,WICHITA,...,33.0,29.0,40.0,62.0,NaN,NaN,31.0,0.0,NaN,0.7658
986674,1124087143,MOULI,KONDA,B,MD,M,I,777 KIMOLE LN,SUITE 260,ADRIAN,...,18.0,33.0,58.0,70.0,38.0,5.0,39.0,3.0,3.0,1.1363
986675,1366635161,DRAGHINAS,DAVID,NaN,M.D.,M,I,34800 BOB WILSON DR,NMCSD,SAN DIEGO,...,35.0,33.0,53.0,75.0,53.0,11.0,39.0,NaN,NaN,1.4547

In [116]:
l1 = df["Provider Type of the Provider"].unique()
print(li)

['Allergists' 'Nurse Practitioner' 'Family Practice' 'Internal Medicine'
 'Optometry' 'Physician Assistant' 'Psychiatrists' 'Orthopedic Surgery'
 'Gynecologist' 'Pediatrician' 'Urologists' 'Radiation Oncology'
 'Physical Therapist' 'Podiatrist' 'Dermatology' 'Emergency Medicine'
 'General Practice' 'Neurologists' 'General surgeons' 'Rheumatologists'
 'Chiropractic' 'Otolaryngologists' 'Infectious Disease'
 'Endocrinologists' 'Centralized Flu' 'Ophthalmology' 'Anesthesiologists'
 'Cardiology' 'Oral and maxillofacial surgeons' 'Oncologists'
 'Radiologists' 'Gastroenterologists' 'CRNA' 'Orthopedic surgeons'
 'Physical Medicine and Rehabilitation' 'Sports Medicine'
 'Licensed Clinical Social Worker' 'Pathology'
 'Mass Immunization Roster Biller' 'Addiction Medicine' 'Pain Management'
 'Independent Diagnostic Testing Facility' 'Certified Nurse Midwife'
 'Pulmonologists' 'Vascular Surgery' 'Certified Clinical Nurse Specialist'
 'Audiologist (billing independently)' 'Preventive Medicine'
 'Nephrologists' 'Occupational therapist' 'All Other Suppliers'
 'Public Health Welfare Agency' 'Ambulatory Surgical Center'
 'Ambulance Service Supplier' 'Speech Language Pathologist'
 'Oral Surgery (dentists only)' 'Nuclear Medicine' 'Bariatrician'
 'Osteopathic Manipulative Medicine' 'Surgical Oncology'
 'Thoracic Surgery' 'Clinical Laboratory' 'Critical Care (Intensivists)'
 'Unknown Physician Specialty Code' 'Cardiac Electrophysiology'
 'Geriatric Medicine' 'Hand Surgery'
 'Multispecialty Clinic/Group Practice' 'Cardiac surgeons'
 'Psychologist (billing independently)' 'Interventional Pain Management'
 'Hospice and Palliative Care' 'Hematology' 'Sleep Medicine'
 'Colorectal Surgery (formerly proctology)' 'Geriatric Psychiatry'
 'Peripheral Vascular Disease' 'Portable X-ray' 'Neuropsychiatry'
 'Radiation Therapy' 'Mammographic Screening Center'
 'Slide Preparation Facility' 'Unknown Supplier/Provider' 'Pharmacy'
 'Interventional Cardiology']

In [117]:
l2=df["State Code of the Provider"].unique()

In [118]:
print(len(l1))
print(len(l2))

21
59

In [125]:
dfnew=pd.DataFrame()
for speciality in l1:
    print(speciality)
    for state in l2:
        dfsubset=df[df["Provider Type of the Provider"]==speciality]
        dfsubset=dfsubset[dfsubset["State Code of the Provider"]==state]
        if len(dfsubset)>=100:
            dfsubset=dfsubset.sample(100)
        dfnew=dfnew.append(dfsubset, ignore_index=True)

Allergists
Psychiatrists
Gynecologist
Pediatrician
Urologists
Podiatrist
Neurologists
General surgeons
Rheumatologists
Otolaryngologists
Endocrinologists
Anesthesiologists
Oral and maxillofacial surgeons
Oncologists
Radiologists
Gastroenterologists
Orthopedic surgeons
Pulmonologists
Nephrologists
Bariatrician
Cardiac surgeons

In [126]:
dfnew

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,Percent (%) of Beneficiaries Identified With Depression,Percent (%) of Beneficiaries Identified With Diabetes,Percent (%) of Beneficiaries Identified With Hyperlipidemia,Percent (%) of Beneficiaries Identified With Hypertension,Percent (%) of Beneficiaries Identified With Ischemic Heart Disease,Percent (%) of Beneficiaries Identified With Osteoporosis,Percent (%) of Beneficiaries Identified With Rheumatoid Arthritis / Osteoarthritis,Percent (%) of Beneficiaries Identified With Schizophrenia / Other Psychotic Disorders,Percent (%) of Beneficiaries Identified With Stroke,Average HCC Risk Score of Beneficiaries
0,1659374411,MAHR,TODD,A,MD,M,I,1836 SOUTH AVE,NaN,LA CROSSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.1238
1,1114999638,CHUDNOW,MELISSA,L,M.D.,F,I,10610 N. PORT WASHINGTON ROAD,NaN,MEQUON,...,22.0,22.0,54.0,54.0,31.0,NaN,29.0,NaN,NaN,1.1066
2,1629118211,GONZAGA,KATHERINE,A,MD,F,I,6408 COPPS AVE,NaN,MONONA,...,NaN,NaN,54.0,54.0,30.0,NaN,54.0,0.0,0.0,1.2939
3,1326299488,THEODOROPOULOS,DEMETRIOS,S,M.D.,M,I,2727 MIDWEST DRIVE,NaN,ONALASKA,...,16.0,19.0,41.0,51.0,17.0,NaN,39.0,0.0,NaN,0.6402
4,1285800367,KONETZKI,WAYNE,H,M.D.,M,I,403 N GRAND AVE,NaN,WAUKESHA,...,21.0,14.0,67.0,37.0,16.0,NaN,41.0,NaN,NaN,0.8319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74941,1346289618,REYNOLDS,TOMMY,R,MD,M,I,4520 W 69TH ST,NaN,SIOUX FALLS,...,19.0,35.0,71.0,75.0,63.0,6.0,31.0,4.0,9.0,1.3490
74942,1134174865,MEYER,PAUL,E,MD,M,I,4520 W 69TH ST,NaN,SIOUX FALLS,...,26.0,34.0,75.0,75.0,75.0,7.0,29.0,6.0,8.0,1.2532
74943,1649385451,FELDHAUS,STEVEN,J,M.D.,M,I,4520 W 69TH ST,NaN,SIOUX FALLS,...,19.0,37.0,75.0,75.0,75.0,7.0,27.0,NaN,7.0,1.3592
74944,1811985211,ANDREONE,PETER,A,MD,M,I,4520 W 69TH ST,NaN,SIOUX FALLS,...,24.0,36.0,75.0,75.0,75.0,9.0,25.0,NaN,NaN,1.2668
74945,1902883747,TAKARA,JAMES,P,MD,M,I,4150 FIFTH STREET,NaN,RAPID CITY,...,26.0,39.0,72.0,75.0,75.0,NaN,36.0,NaN,12.0,1.7070

In [128]:
dfnew.to_csv (r'doctor_database.csv', index = False, header=True)